apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: demo-voting-app
    name: result-service-pod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: demo-voting-app
    name: result-app-pod