apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sidecar
  name: sidecar-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
    targetPort: 80
  selector:
    app: sidecar
status:
  loadBalancer: {}
