apiVersion: apps/v1
kind:  ReplicaSet

metadata:
  name: replicaset
  labels:
    app: replicaset-app
    type: front-end

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp

    spec:
      containers:
      - name: nginx-container
        image: nginx

  replicas: 7

  selector:
    matchLabels:
      app: myapp
